# .koyeb.yaml
name: laravel-koyeb
region: washington-dc

services:
  - name: app
    type: web
    build:
      builder: heroku/buildpacks:20
      build_command: |
        composer install --no-dev --optimize-autoloader
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
        npm ci
        npm run build
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
    run_command: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=$PORT